const IMAGES = {
    versace : new URL('./assets/images/brands/versace.png',import.meta.url).href,
    zara : new URL('./assets/images/brands/zara.png',import.meta.url).href,
    gucci : new URL('./assets/images/brands/gucci.png',import.meta.url).href,
    prada : new URL('./assets/images/brands/prada.png',import.meta.url).href,
    calvin : new URL('./assets/images/brands/calvin.png',import.meta.url).href,
    versaceDesktop : new URL('./assets/images/brands/versace-desktop.svg',import.meta.url).href,
    zaraDesktop : new URL('./assets/images/brands/zara-desktop.png',import.meta.url).href,
    pradaDesktop : new URL('./assets/images/brands/prada-desktop.svg',import.meta.url).href,
    gucciDesktop : new URL('./assets/images/brands/gucci-desktop.svg',import.meta.url).href,
    calvinDesktop : new URL('./assets/images/brands/calvin-desktop.svg',import.meta.url).href,
    tapede : new URL('./assets/images/products/tapede-tails.svg',import.meta.url).href,
    fitJeans : new URL('./assets/images/products/fit-jeans.svg',import.meta.url).href,
    checkeredShirt: new URL('./assets/images/products/checkered-shirt.svg',import.meta.url).href,
    stripedT : new URL('./assets/images/products/striped-t-shirt.svg',import.meta.url).href,
    star_full : new URL('./assets/images/products/star-full.svg',import.meta.url).href,
    star_half : new URL('./assets/images/products/star-half.svg',import.meta.url).href,
    blue_check : new URL('./assets/images/comments/blue-check-mark.svg',import.meta.url).href,
    casual :  new URL('./assets/images/browses/casual.svg',import.meta.url).href,
    formal :  new URL('./assets/images/browses/formal.svg',import.meta.url).href,
    party :  new URL('./assets/images/browses/party.svg',import.meta.url).href,
    gym :  new URL('./assets/images/browses/gym.svg',import.meta.url).href,
    casualDesktop :  new URL('./assets/images/browses/casual-desktop.svg',import.meta.url).href,
    formalDesktop :  new URL('./assets/images/browses/formal-desktop.svg',import.meta.url).href,
    partyDesktop :  new URL('./assets/images/browses/party-desktop.svg',import.meta.url).href,
    gymDesktop :  new URL('./assets/images/browses/gym-desktop.svg',import.meta.url).href,
    icon_visa  :  new URL('./assets/images/footers/visa.svg',import.meta.url).href,
    icon_master  :  new URL('./assets/images/footers/master.svg',import.meta.url).href,
    icon_paypay  :  new URL('./assets/images/footers/paypal.svg',import.meta.url).href,
    icon_ippay  :  new URL('./assets/images/footers/ip-pay.svg',import.meta.url).href,
    icon_g_pay : new URL('./assets/images/footers/g-pay.svg',import.meta.url).href,
    icon_star_banner: new URL('./assets/images/banners/star.svg',import.meta.url).href,
  
}
// eslint-disable-next-line react-refresh/only-export-components
export default IMAGES